[package]
edition = "2021"
name = "zbuild"
version = "0.1.0"

[dependencies]

# Futures
tokio = {version = "1.20.1", features = ["full"]}

# Cmd
clap = {version = "3.2.17", features = ["derive"]}

# Logging
tracing = "0.1.36"
tracing-subscriber = {version = "0.3.15", features = ["env-filter"]}

# Error handling
anyhow = "1.0.61"

# Serde
serde = {version = "1.0.143", features = ["derive"]}
serde_yaml = "0.9.9"

# Util
async-recursion = "1.0.0"
byteorder = "1.4.3"
dashmap = "5.3.4"
filetime = "0.2.17"
futures = "0.3.23"
itertools = "0.10.3"
