[package]
edition     = "2024"
name        = "zbuild"
description = "Make-like build system"
license     = "MIT OR Apache-2.0"
version     = "0.1.9"
repository  = "https://github.com/zenithsiz/zbuild"
publish     = ["filipejr"]

[dependencies]

async-broadcast       = "0.7.2"
clap                  = { features = ["derive"], version = "4.5.27" }
console-subscriber    = { optional = true, version = "0.4.1" }
dashmap               = "6.1.0"
futures               = "0.3.31"
indexmap              = "2.7.1"
indicatif             = "0.17.11"
itertools             = "0.14.0"
notify                = "8.0.0"
notify-debouncer-full = "0.5.0"
pin-project           = "1.1.8"
smallvec              = { features = ["may_dangle"], version = "1.13.2" }
tokio                 = { features = ["full"], version = "1.43.0" }
tokio-stream          = "0.1.17"
tracing               = "0.1.41"
tracing-subscriber    = { features = ["env-filter"], version = "0.3.19" }
unicode-ident         = "1.0.16"
yoke                  = "0.7.5"
zutil-app-error       = { git = "https://github.com/Zenithsiz/zutil", rev = "5363bba6ced162185a1eb5a132cce499bfc5d818" }

[dev-dependencies]

tempfile     = "3.16.0"
tracing-test = { version = "0.2.5", features = ["no-env-filter"] }

[features]

tokio-console = ["dep:console-subscriber"]

[lints]

# This project doesn't require unsafe code (outside of some modules)
rust.unsafe_code            = "deny"
rust.unsafe_op_in_unsafe_fn = "deny"

# Group lints
clippy.pedantic = { level = "warn", priority = -1 }
clippy.nursery  = { level = "warn", priority = -1 }

# Prefer `expect` instead of `unwrap`
clippy.unwrap_used = "deny"
clippy.expect_used = "allow"

# We must specify `'_` to avoid surprises
rust.elided_lifetimes_in_paths = "deny"

# `Debug` / `Copy` should be implemented wherever possible
rust.missing_copy_implementations  = "warn"
rust.missing_debug_implementations = "warn"

# Misc.
rust.noop_method_call               = "warn"
rust.unused_results                 = "warn"
rust.explicit_outlives_requirements = "warn"
rust.meta_variable_misuse           = "warn"
rust.must_not_suspend               = "warn"
rust.single_use_lifetimes           = "warn"
rust.trivial_numeric_casts          = "warn"
rust.unused_lifetimes               = "warn"
rust.unused_macro_rules             = "warn"
rust.variant_size_differences       = "warn"
clippy.let_underscore_untyped       = "warn"

# False positives
clippy.significant_drop_tightening = "allow"

# Style
clippy.implicit_return          = "allow"
clippy.multiple_inherent_impl   = "allow"
clippy.pattern_type_mismatch    = "allow"
clippy.match_bool               = "allow"
clippy.single_match_else        = "allow" # Note: `match` reads easier than `if / else`
clippy.option_if_let_else       = "allow"
clippy.self_named_module_files  = "allow"
clippy.items_after_statements   = "allow"
clippy.module_name_repetitions  = "allow"
clippy.module_inception         = "allow"
clippy.separated_literal_suffix = "allow"
clippy.ref_patterns             = "allow" # Matching on a vale and adding `ref` is easier than matching on ref and de-referencing values within the body


# Callers don't care about which error happened.
clippy.missing_errors_doc = "allow"

# Too noisy with self-contained panics that the caller will never see.
clippy.missing_panics_doc = "allow"

# This is too prevalent on generic functions, which we don't want to ALWAYS be `Send`
clippy.future_not_send = "allow"

# We want to format paths with quotes
clippy.unnecessary_debug_formatting = "allow"
