[package]
name                  = "zbuild-bin"
description.workspace = true
edition.workspace     = true
license.workspace     = true
publish.workspace     = true
repository.workspace  = true
version.workspace     = true

[[bin]]
path = "src/main.rs"
name = "zbuild"

[features]

tokio-console = ["dep:console-subscriber"]

[dependencies]

# Workspace
zbuild = { workspace = true }

app-error          = { workspace = true }
clap               = { features = ["derive"], workspace = true }
console-subscriber = { optional = true, workspace = true }
itertools          = { workspace = true }
tokio              = { features = ["full"], workspace = true }
tracing            = { workspace = true }
tracing-log        = { workspace = true }
tracing-subscriber = { features = ["env-filter"], workspace = true }
zutil-logger       = { workspace = true }

[lints]
workspace = true
